default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: catalogbuilder
  password: '6Iwh8HLn/mR9upEyxS+4ag=='

development:
  <<: *default
  database: catalogbuilder_dev

test:
  <<: *default
  database: catalogbuilder_test

production:
  <<: *default
  database: catalogbuilder 
