default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: catalogbuilder
  password: <%= ENV['CATALOGBUILDER_DB_PWD'] %>

development:
  <<: *default
  database: catalogbuilder_dev

test:
  <<: *default
  database: catalogbuilder_test

production:
  <<: *default
  database: catalogbuilder 
